"""8e.7 regression guard for corrected wall, camera rendering, measurement, and persistence."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'templates'/'index.html').read_text(encoding='utf-8')
JS=(ROOT/'static'/'viewer.js').read_text(encoding='utf-8')
for marker in ('id="calibrateScaleTool"','id="measureDistanceTool"','id="measurementStatus"','Measurement Tools','Help','About','value="hvdcMm"','video-wall-tile-controls','measurement-magnifier','.menu-group.collapsed .measurement-status'):
    assert marker in HTML, f'Missing 8e.7 corrected control: {marker}'
for marker in ("const PROJECT_SCHEMA_VERSION = 6;","function beginMeasurementTool(mode)","function closestPointOnTriangleEdge(intersection)","function updateMeasurementMagnifier(event, pick)","function renderMeasurementMagnifier()","measurementMagnifierRenderer","measurementPointerMoved","orbitControls.enabled = true","function renderCameraView(targetRenderer, targetCamera)","renderCamera.far = Math.max(renderCamera.near + 0.01, projectionDistance)","cameraItem.data.viewportPalette = selectedViewportPalette","source.item.data.viewportPalette = record.palette","downloadRendererCapture(wallRenderer, source.label)","adjustCameraPtzFromView(source.item","measurements: measurements.map(record => ({","restoreMeasurements(project.measurements)","referenceImages: sceneObjects","preferences: { ...preferences }","function showMeasurementEdgeOutline(intersection)","measurementOutlinedFaceKey","vertices[2], vertices[0]","line.renderOrder = 1000","depthTest: false","function createMeasurementLabel(record, start, end)","function orientMeasurementLabels(camera)","const reverseForPointSequence = firstScreenX > secondScreenX","orientMeasurementLabels(targetCamera)","measurementDisplayId","displayId: nextMeasurementDisplayId()","const DEFAULT_MEASUREMENT_MAGNIFICATION = 3;","loupeMagnification: 3","Math.min(20, Math.max(2, loupeMagnification))","measurementMagnifierBadge.textContent","measurementMagnifierCamera.setViewOffset(width, height, offsetX, offsetY, cropSize, cropSize)","const cropSize = Math.max(1, Math.min(width, height) / magnification)","measurementMagnifierCamera.zoom = viewerCamera.zoom","child.material?.map?.dispose?.()"):
    assert marker in JS, f'Missing 8e.7 corrected behavior: {marker}'
assert JS.index("preferences.modelImportPreset === 'hvdcMm'") < JS.index('model.scale.multiplyScalar(importScale)')
print('8e.7 live-lens/navigation/camera/persistence guard passed')