import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../static/viewer.js',import.meta.url),'utf8');
const start=source.indexOf('function getWallColumns(count, selection)');
const end=source.indexOf('function syncWallCamera',start);
assert.ok(start>=0 && end>start,'Wall column function was not found');
const sandbox={Math};
vm.runInNewContext(`${source.slice(start,end)}\nthis.getWallColumns=getWallColumns;`,sandbox);
for(const [count,expected] of [[1,1],[2,2],[4,2],[5,3],[9,3],[10,4],[16,4],[17,5]]) assert.equal(sandbox.getWallColumns(count,'auto'),expected);
assert.equal(sandbox.getWallColumns(12,'3'),3);
console.log('8e.7 Video Wall layout runtime tests passed');